# Generated by Django 3.1.5 on 2021-01-26 18:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_per', models.CharField(max_length=10)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Advertisement'), ('project-support', 'Project Support')], max_length=32)),
                ('start_date', models.DateField()),
                ('finished', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=100)),
                ('status_updated_on', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_client', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.CharField(max_length=10)),
                ('leave_type', models.CharField(max_length=10)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobAllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Advertisement'), ('project-support', 'Project Support')], max_length=32)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.service')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField()),
                ('service', models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Advertisement'), ('project-support', 'Project Support')], max_length=32)),
                ('status', models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Advertisement'), ('project-support', 'Project Support')], max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
