# Generated by Django 3.1.5 on 2021-01-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Advertisement'), ('project-support', 'Project Support')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='clientrequests',
            name='status',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Advertisement'), ('project-support', 'Project Support')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='joballocationrequest',
            name='status',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Advertisement'), ('project-support', 'Project Support')], default='pending', max_length=32),
        ),
    ]
