# Generated by Django 3.1.5 on 2021-01-26 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solutions', '0003_auto_20210126_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequests',
            name='service',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Digital Marketing'), ('project-support', 'Project Support')], max_length=32),
        ),
        migrations.AlterField(
            model_name='clientrequests',
            name='status',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Digital Marketing'), ('project-support', 'Project Support')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='joballocationrequest',
            name='status',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Digital Marketing'), ('project-support', 'Project Support')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Digital Marketing'), ('project-support', 'Project Support')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Digital Marketing'), ('project-support', 'Project Support')], max_length=32),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
