# Generated by Django 3.1.5 on 2021-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_auto_20210126_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='Project Started', max_length=32),
        ),
    ]
