# Generated by Django 3.1.5 on 2021-01-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequests',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
