# Generated by Django 3.1.5 on 2021-01-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_auto_20210127_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='added_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
