# Generated by Django 3.1.5 on 2021-01-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0009_auto_20210130_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('pending', 'Pending')], default='pending', max_length=32),
        ),
    ]
