# Generated by Django 3.1.5 on 2021-01-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='service',
            field=models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('graphic-design', 'Graphic Design'), ('application-development', 'Application Development'), ('advertisement-creation', 'Advertisement Creation'), ('digital-marketing', 'Digital Marketing'), ('project-support', 'Project Support')], max_length=32),
        ),
    ]
